#!/usr/bin/zsh

cd $(dirname $0)
. ./config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

PANEL_FIFO=$TMPDIR/panel

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Title information
xtitle -sf 'T%s' > "$PANEL_FIFO" &

# WM status
bspc control --subscribe > "$PANEL_FIFO" &

# Conky
conky -c ./conkyrc > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | \
    ./panel_bar | \
    bar -f $FONT \
        -F $BASE0 \
        -B $BASE03 \
        -g $PANEL_GEOMETRY \
        -u $LINEHEIGHT &

wait
