#!/usr/bin/zsh

# Source colors
source colors

## Adopt orphan windows
bspc control --adopt-orphans

## Setup desktops
bspc monitor eDP1 -d {1,2,3,4,5,6,7,8,9}

# General
bspc config auto_alternate true
bspc config auto_cancel    true

# Visual
bspc config top_padding	       $BSPWM_PANEL_HEIGHT
bspc config border_width       0
bspc config window_gap         5
bspc config split_ratio        0.50
bspc config borderless_monocle true
bspc config gapless_monocle    true

# Pointer
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

# Colors
# Normal
bspc config focused_border_color 	${blue#??}
bspc config active_border_color		${violet#??}
bspc config normal_border_color 	${fg#??}
bspc config presel_border_color 	${magenta#??}
bspc config urgent_border_color 	${red#??}

# Locked
bspc config focused_locked_border_color ${blue#??}
bspc config active_locked_border_color  ${orange#??}
bspc config normal_locked_border_color	${orange#??}

# Sticky
bspc config focused_sticky_border_color ${blue#??}
bspc config active_sticky_border_color  ${yellow#??}
bspc config normal_sticky_border_color	${yellow#??}

# Private
bspc config focused_private_border_color ${blue#??}
bspc config active_private_border_color  ${green#??}
bspc config normal_private_border_color	 ${green#??}

# Rules
bspc rule -a Firefox desktop=^2

panel &
