# Source Xresources
xrdb "$XDG_CONFIG_HOME/xorg/Xresources"

# Configure monitors
xrandr --output DVI-1 --left-of DVI-0

# Set cursor
xsetroot -cursor_name=left_ptr &

# Run xmodmap
xmodmap "$XDG_CONFIG_HOME/xorg/xmodmap" &

# Setup wallpaper
. $HOME/.fehbg &

# Sync clipboard
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# urxvt-daemon
urxvtd -q -o -f &

# hide mouse
unclutter -idle 3 &

# window manager
exec $XDG_CONFIG_HOME/bspwm/wm
