#!/usr/bin/zsh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Title information
xtitle -sf 'T%s' > "$BSPWM_PANEL" &

# Clock
clock -sf 'S%a %H:%M' > "$BSPWM_PANEL" &

# WM status
bspc control --subscribe > "$BSPWM_PANEL" &

# Battery
panel_battery > "$BSPWM_PANEL" &

cat "$BSPWM_PANEL" | panel_bar | bar &

wait
