#!/usr/bin/zsh
#
# Example panel for LemonBoy's bar

COLOR_FOREGROUND=$fg
COLOR_BACKGROUND=$bg
COLOR_FOCUSED_OCCUPIED_FG=$blue
COLOR_FOCUSED_OCCUPIED_BG=$bg
COLOR_FOCUSED_FREE_FG=$magenta
COLOR_FOCUSED_FREE_BG=$bg
COLOR_FOCUSED_URGENT_FG=$blue
COLOR_FOCUSED_URGENT_BG=$orange
COLOR_OCCUPIED_FG=$violet
COLOR_OCCUPIED_BG=$bg
COLOR_FREE_FG=$fg
COLOR_FREE_BG=$bg
COLOR_URGENT_FG=$yellow
COLOR_URGENT_BG=$red
COLOR_LAYOUT_FG=$blue
COLOR_LAYOUT_BG=$bg
COLOR_TITLE_FG=$blue
COLOR_TITLE_BG=$bg
COLOR_STATUS_FG=$blue
COLOR_STATUS_BG=$bg
COLOR_SEP_FG=$base3
COLOR_SEP_BG=$bg
COLOR_BAT_FULL_FG=$blue
COLOR_BAT_FULL_BG=$bg
COLOR_BAT_DISC_FG=$red
COLOR_BAT_DISC_BG=$bg
COLOR_BAT_CHAR_FG=$green
COLOR_BAT_CHAR_BG=$bg
COLOR_BAT_NOTP_FG=$red
COLOR_BAT_NOTP_BG=$bg
COLOR_BAT_EMPT_FG=$yellow
COLOR_BAT_EMPT_BG=$red
COLOR_BAT_UNKN_FG=$yellow
COLOR_BAT_UNKN_BG=$bg

typeset -A bat_icon
bat_icon=[D]="↓"
bat_icon=[C]="↑"
bat_icon=[F]="∞"
bat_icon=[E]="×"
bat_icon=[N]="¬"
bat_icon=[U]="?"

lsep="%{F$COLOR_SEP_FG}%{B$COLOR_SEP_BG}<%{F-}%{B-}"
rsep="%{F$COLOR_SEP_FG}%{B$COLOR_SEP_BG}>%{F-}%{B-}"
csep="%{F$COLOR_SEP_FG}%{B$COLOR_SEP_BG}|%{F-}%{B-}"

blue="%{F$blue}"
base3="%{F$base3}"
deffg="%{F-}"
defbg="%{B-}"

while read -r line ; do
    case $line in
        TITLE*)
            # title
            title=${${line#TITLE}[1,50]}
            maxlen=50
            pad=$((maxlen/2))
            len=${#title}
            if [[ $len -lt $maxlen ]]; then
                ltitle=${(l:$pad:: :)title[1,$((len/2))]}
                rtitle=${(r:$pad:: :)title[$((len/2+1)),$len]}
                title=$blue$ltitle$
                title="$lsep%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}$ltitle$rtitle$rsep"
            fi
            ;;
        TIME*)
            # clock
            time="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#TIME}"
            ;;
        DATE*)
            # date
            date="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#DATE}"
            ;;
        BATSTAT*)
            # battery status
            batstat=${${line#BATSTAT}[1]}
            baticon=$bat_icon[$batstat]
            case $batstat in
                F)
                    batfg=$COLOR_BAT_FULL_FG
                    batbg=$COLOR_BAT_FULL_BG
                    ;;
                C)
                    batfg=$COLOR_BAT_CHAR_FG
                    batbg=$COLOR_BAT_CHAR_BG
                    ;;
                D)
                    batfg=$COLOR_BAT_DISC_FG
                    batbg=$COLOR_BAT_DISC_BG
                    ;;
                E)
                    batfg=$COLOR_BAT_EMPT_FG
                    batbg=$COLOR_BAT_EMPT_BG
                    ;;
                N)
                    batfg=$COLOR_BAT_NOTP_FG
                    batbg=$COLOR_BAT_NOTP_BG
                    ;;
                U)
                    batfg=$COLOR_BAT_UNKN_FG
                    batbg=$COLOR_BAT_UNKN_BG
                    ;;
            esac
            ;;
        BATPERC*)
            # battery
            batperc=${(l:2:: :)line#BATPERC}
            [[ $batperc == "00" ]] && batperc="99"
            bat=%{F$batfg}%{B$batbg}$baticon$batperc
            ;;
        CPU*)
            # cpu
            cpu=${(l:2:: :)line#CPU}
            [[ $cpu == "00" ]] && cpu="99"
            cpu=$blue$cpu
            ;;
        MEM*)
            # memory
            mem=${(l:2:: :)line#MEM}
            [[ $cpu == "00" ]] && cpu="99"
            mem=$blue$mem
            ;;
        VOL*)
            vol=${(l:2:: :)line#VOL}
            [[ $vol == "00" ]] && vol="99"
            vol=$blue$vol
            ;;
        NET*)
            net=${(l:2:: :)line#NET}
            [[ $net == "00" ]] && net="99"
            net=$blue$net
            ;;
        W*)
            # bspwm internal state
            wm=""
            set -- ${(s/:/)line#W}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    M*)
                        monitor=$name
                        ;;
                    O*)
                        # focused occupied desktop
                        wm="$wm%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u}${name}%{-u}"
                        ;;
                    F*)
                        # focused free desktop
                        wm="$wm%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u}${name}%{-u}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm="$wm%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}${name}%{-u}"
                        ;;
                    o*)
                        # occupied desktop
                        wm="$wm%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}$name"
                        ;;
                    f*)
                        # free desktop
                        wm="$wm%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}$name"
                        ;;
                    u*)
                        # urgent desktop
                        wm="$wm%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}$name"
                        ;;
                    L*)
                        # layout
                        lay=${(U)name[1]}
                        lay="%{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG}$lay$defbg$deffg"
                        wm="$lsep$lay$wm$rsep"
                        ;;
                esac
                shift
            done
            ;;
        *)
            print $line
            ;;
    esac
    sys=$lsep$vol$csep$cpu$csep$mem$csep$net$csep$bat$rsep
    dt=$(printf "%s %s %s" "$lsep$date" "${base3}-$deffg" "$time$rsep")

    print "%{l} $wm%{c}$title%{r}$sys$dt "

done

