#!/usr/bin/zsh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Title information
xtitle -sf 'TITLE%s' > "$BSPWM_PANEL" &

# WM status
bspc control --subscribe > "$BSPWM_PANEL" &

# Conky
conky > "$BSPWM_PANEL" &

cat "$BSPWM_PANEL" | panel_bar | bar -g x$BSPWM_PANEL_HEIGHT++ -f "-*-terminus-medium-r-*-*-14-*-*-*-*-*-*-*" -u 1 -B $bg -F $fg &

wait
